    figureW = 1100;
    figureH = 600;
global openAgain;
openAgain = 0;
global pathname; 
pathname = 'D:\MART\Images';

handleFigure = figure(...
    'position',[100, 70, figureW, figureH] ,...
    'Name','MyGui',...
    'menu','none',...
    'NumberTitle','off',...
    'Interruptible','off',...
    'Resize','off'...
    );

global handleAxes;
handleAxes = axes(...
    'units','normalized',...
    'Position', [0.01, 0.62, 0.15, 0.28],...
    'Interruptible','off',...
    'ydir', 'reverse', ...
    'Box','on',...
    'XTick',[],...
    'YTick',[],...
    'Visible','off'...
    );

global chosenImg;
chosenImg = image(...
    'Interruptible','off',...
    'Parent', handleAxes,...
    'Visible','off'...
);

buttonOpen = uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',[0.01 0.920 0.08 0.054], ...
   'String','Open an Image.', ...
   'callback','open');

buttonRun = uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',[0.01 0.560 0.04 0.054], ...
   'String','Run', ...
   'callback','run',...
   'Visible','off');

buttonNext = uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',[0.01 0.560 0.04 0.054], ...
   'String','Next', ...
   'callback','next',...
   'Visible','off');

buttonPrev = uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',[0.01 0.500 0.04 0.054], ...
   'String','Prev', ...
   'callback','prev',...
   'Visible','off');

global result;
result = uicontrol(...
    'Style', 'text', ...
    'Units','normalized', ...
    'FontSize', 10, ...
    'Position', [0.01 0.400 0.12 0.044],...
    'String', '',...
    'Visible','off'...
    );
	
global resultFileTips;
resultFileTips = uicontrol(...
    'Style', 'text', ...
    'Units','normalized', ...
    'FontSize', 10, ...
    'Position', [0.01 0.250 0.15 0.14],...
    'String', 'Click on result.txt, you will have to wait a moment, don not worry, While the file result.txt is ok, I will remind you.^-^',...
    'Visible','on'...
    );

global resultFileButton
resultFileButton = uicontrol( ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',[0.01 0.150 0.06 0.054], ...
   'String','result.txt', ...
   'callback','resultToFile',...
   'Visible','on');

global imagesAxeses;
    
imgWidth = figureW * 0.8 / 5;
imgHeight = figureH * 0.9 / 5;
    
for row = 1 : 5
    for col = 1 : 5
       index = (row - 1) * 5 + col;
        imagesAxeses(index) = axes( ...
            'Position', [ ((col - 1) * (imgWidth * 1.02) + 200) / figureW ...
               ((5 - row) * (imgHeight * 1.05)+10) / figureH ...
                imgWidth / figureW ...
                imgHeight / figureH], ...
             'Xtick', [], ...
             'Ytick', [], ...
             'ydir', 'reverse', ...
             'Visible','off'...
                );
   end
end

filePath = 'D:\MART\Image Database';
%global gramhs;
%global gramss;
%global gramvs;
%[gramhs, gramss, gramvs] = loadDataGUI(filePath);

global rgbHiss;
rgbHiss = loadDataGUI(filePath);
    